CadernetaVacinal/Models/ErrorViewModel.cs
namespace CadernetaVacinal.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadernetaVacinal/Models/Vacina.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace CadernetaVacinal.Models;

public class Vacina
{
    [Key]
    [Required]
    [DisplayName("Código")]
    public int VacinaId { get; set; }

    [Required(ErrorMessage = "O lote é obrigatório.")]
    [StringLength(40, ErrorMessage = "O lote deve ter no máximo 40 caracteres.")]
    public string Lote { get; set; } = string.Empty;

    [Required(ErrorMessage = "O nome da vacina é obrigatório.")]
    [StringLength(100, ErrorMessage = "O nome da vacina deve ter no máximo 100 caracteres.")]
    [DisplayName("Nome da Vacina")]
    public string NomeVacina { get; set; } = string.Empty;

    [Required(ErrorMessage = "O local é obrigatório.")]
    [StringLength(100, ErrorMessage = "O local deve ter no máximo 100 caracteres.")]
    public string Local { get; set; } = string.Empty;

    [Required(ErrorMessage = "A data de vacinação é obrigatória.")]
    [DisplayName("Data da Vacinação")]
    [DataType(DataType.Date, ErrorMessage = "Data de vacinação inválida.")]
    public DateTime DataVacinação { get; set; }

    [DisplayName("Dose Única")]
    public bool Dose { get; set; }

    [Required(ErrorMessage = "O CPF do Paciente é obrigatório.")]
    [StringLength(11, ErrorMessage = "O CPF deve ter no máximo 11 caracteres.")]
    [DisplayName("CPF do Paciente")]
    public string CPF { get; set; } = string.Empty;

    [Required(ErrorMessage = "O Nomme do Paciente é obrigatório.")]
    [StringLength(100, ErrorMessage = "O Nome deve ter no máximo 100 caracteres.")]
    [DisplayName("Nome do Paciente")]
    public string Nome { get; set; } = string.Empty;


    [Required(ErrorMessage = "A matrícula do funcionário é obrigatório.")]
    [DisplayName("Matrícula do Funcionário")]
    public int Matricula { get; set; }

    [Required(ErrorMessage = "O nome do funcionário é obrigatório.")]
    [StringLength(100, ErrorMessage = "O nome do funcionário deve ter no máximo 100 caracteres.")]
    [DisplayName("Funcionário")]
    public string Funcionario { get; set; } = string.Empty;

    [DisplayName("Usuário")]
    public string User { get; set; } = string.Empty;
}

CadernetaVacinal/Controllers/HomeController.cs
using CadernetaVacinal.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CadernetaVacinal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadernetaVacinal/Controllers/VacinasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CadernetaVacinal.Data;
using CadernetaVacinal.Models;
using Microsoft.AspNetCore.Authorization;

namespace CadernetaVacinal.Controllers;

[Authorize] 
public class VacinasController : Controller
{
    private readonly ApplicationDbContext _context;

    public VacinasController(ApplicationDbContext context)
    {
        _context = context;
    }

    // GET: Vacinas
    public async Task<IActionResult> Index()
    {
          return _context.Vacinas != null ? 
                      View(await _context.Vacinas
                      .ToListAsync()) :
                      Problem("Entity set 'ApplicationDbContext.Vacinas'  is null.");
    }

    // GET: Vacinas/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.Vacinas == null)
        {
            return NotFound();
        }

        var vacina = await _context.Vacinas
            .FirstOrDefaultAsync(m => m.VacinaId == id);
        if (vacina == null)
        {
            return NotFound();
        }
                
        return View(vacina);
    }

    // GET: Vacinas/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Vacinas/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("VacinaId,Lote,NomeVacina,Local,DataVacinação,Dose,CPF,Nome,Matricula,Funcionario,User")] Vacina vacina)
    {
        if (ModelState.IsValid)
        {
            vacina.User = User.Identity.Name; 
            _context.Add(vacina);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(vacina);
    }

    // GET: Vacinas/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || _context.Vacinas == null)
        {
            return NotFound();
        }

        var vacina = await _context.Vacinas.FindAsync(id);
        if (vacina == null)
        {
            return NotFound();
        }

        if (User.Identity.Name != "admin@admin.com")
        {
            if (vacina.User != User.Identity.Name)
            {
                return View("Denied");
            }
        }

            

        return View(vacina);
    }

    // POST: Vacinas/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("VacinaId,Lote,NomeVacina,Local,DataVacinação,Dose,CPF,Nome,Matricula,Funcionario")] Vacina vacina)
    {
        if (id != vacina.VacinaId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                vacina.User = User.Identity.Name;
                _context.Update(vacina);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!VacinaExists(vacina.VacinaId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(vacina);
    }

    // GET: Vacinas/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.Vacinas == null)
        {
            return NotFound();
        }

        var vacina = await _context.Vacinas
            .FirstOrDefaultAsync(m => m.VacinaId == id);
        if (vacina == null)
        {
            return NotFound();
        }

        if (User.Identity.Name != "admin@admin.com")
        {
            if (vacina.User != User.Identity.Name)
            {
                return View("Denied");
            }
        }

            

        return View(vacina);
    }

    // POST: Vacinas/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (_context.Vacinas == null)
        {
            return Problem("Entity set 'ApplicationDbContext.Vacinas'  is null.");
        }
        var vacina = await _context.Vacinas.FindAsync(id);
        if (vacina != null)
        {
            _context.Vacinas.Remove(vacina);
        }
        
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool VacinaExists(int id)
    {
      return (_context.Vacinas?.Any(e => e.VacinaId == id)).GetValueOrDefault();
    }
}

CadernetaVacinal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo</h1>
    <p>"Cuide da sua saúde com facilidade: registre, acompanhe e gerencie todas as suas informações médicas em um só lugar."</p>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-6">
                <img src="img/home.jpg" class="img-fluid">
            </div>
        </div>
    </div>
</div>

CadernetaVacinal/Views/Shared/Denied.cshtml
@{
    ViewBag.Title = "Acesso Negado";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">Acesso Negado</h2>
            <p class="text-center">Desculpe, somente o próprio usuário ou administrador tem permissão para modificar este dado.</p>
            <div class="text-center">
                <img src="/img/acesso negado.jpg" class="img-fluid" alt="Acesso Negado" style="max-width: 200px;">
            </div>
        </div>
    </div>
</div>

CadernetaVacinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Caderneta Vacinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadernetaVacinal.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Caderneta Vacinal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vacinas" asp-action="Index">Vacinas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CadernetaVacinal - <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CadernetaVacinal/Views/Vacinas/Create.cshtml
@model CadernetaVacinal.Models.Vacina

@{
    ViewData["Title"] = "Vacinas";
}

<h1>Inserir Dados</h1>

<h4>Vacina</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Lote" class="control-label"></label>
                <input asp-for="Lote" class="form-control mb-3" placeholder="Insira o lote" />
                <span asp-validation-for="Lote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomeVacina" class="control-label"></label>
                <input asp-for="NomeVacina" class="form-control mb-3" placeholder="Insira o nome da vacina" />
                <span asp-validation-for="NomeVacina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Local" class="control-label"></label>
                <input asp-for="Local" class="form-control mb-3" placeholder="Insira o local" />
                <span asp-validation-for="Local" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataVacinação" class="control-label"></label>
                <input asp-for="DataVacinação" class="form-control mb-3" placeholder="Insira a data da vacinação" />
                <span asp-validation-for="DataVacinação" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input mb-3" asp-for="Dose" /> @Html.DisplayNameFor(model => model.Dose)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control mb-3" placeholder="Insira o CPF" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control mb-3" placeholder="Insira o nome" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control mb-3" placeholder="Insira a matrícula" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Funcionario" class="control-label"></label>
                <input asp-for="Funcionario" class="form-control mb-3" placeholder="Insira o nome do funcionário" />
                <span asp-validation-for="Funcionario" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Inserir" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">| Voltar</a>
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CadernetaVacinal/Views/Vacinas/Delete.cshtml
@model CadernetaVacinal.Models.Vacina

@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar</h1>

<h3>Você tem certeza, essa operação é irreversível!</h3>
<div>
    <h4>Vacina</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lote)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lote)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeVacina)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeVacina)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Local)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Local)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataVacinação)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataVacinação)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dose)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dose)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Funcionario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Funcionario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="VacinaId" />
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Voltar</a>
    </form>
</div>

CadernetaVacinal/Views/Vacinas/Details.cshtml
@model CadernetaVacinal.Models.Vacina

@{
    ViewData["Title"] = "Detalhes dos Registros";
}

<h1>Detalhes</h1>

<div>
    <h4>Vacina</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VacinaId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VacinaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lote)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lote)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeVacina)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeVacina)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Local)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Local)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataVacinação)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataVacinação)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dose)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dose)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Funcionario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Funcionario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.VacinaId" class="btn btn-primary">Editar</a> |
    <a asp-action="Index" class="btn btn-secondary">Voltar</a>
</div>

CadernetaVacinal/Views/Vacinas/Edit.cshtml
@model CadernetaVacinal.Models.Vacina

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Vacina</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="VacinaId" />
            <div class="form-group">
                <label asp-for="Lote" class="control-label"></label>
                <input asp-for="Lote" class="form-control mb-3" />
                <span asp-validation-for="Lote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomeVacina" class="control-label"></label>
                <input asp-for="NomeVacina" class="form-control mb-3" />
                <span asp-validation-for="NomeVacina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Local" class="control-label"></label>
                <input asp-for="Local" class="form-control mb-3" />
                <span asp-validation-for="Local" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataVacinação" class="control-label"></label>
                <input asp-for="DataVacinação" class="form-control mb-3" />
                <span asp-validation-for="DataVacinação" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input mb-3" asp-for="Dose" /> @Html.DisplayNameFor(model => model.Dose)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control mb-3" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control mb-3" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control mb-3" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Funcionario" class="control-label"></label>
                <input asp-for="Funcionario" class="form-control mb-3" />
                <span asp-validation-for="Funcionario" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Voltar</a>
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CadernetaVacinal/Views/Vacinas/Index.cshtml
@model IEnumerable<CadernetaVacinal.Models.Vacina>

@{
    ViewData["Title"] = "Vacinas";
}

<h1>Vacinas</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Inserir Dados</a>
</p>
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.VacinaId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>            
                <th>
                    @Html.DisplayNameFor(model => model.NomeVacina)
                </th>
                <th class="col-md-3">
                    @Html.DisplayNameFor(model => model.User)
                </th>            
                <th class="d-none d-md-table-cell">
                    @Html.DisplayNameFor(model => model.DataVacinação)
                </th>
                        
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.VacinaId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>            
                <td>
                    @Html.DisplayFor(modelItem => item.NomeVacina)
                </td>
                    <td class="col-md-3">
                    @Html.DisplayFor(modelItem => item.User)
                </td>            
                <td class="d-none d-md-table-cell">
                    @Html.DisplayFor(modelItem => item.DataVacinação)
                </td>
            
                <tr>
                    <td colspan="6">

                        <a asp-action="Edit" asp-route-id="@item.VacinaId" class="btn btn-primary">Editar</a> |
                        <a asp-action="Details" asp-route-id="@item.VacinaId" class="btn btn-secondary">Detalhes</a> |
                        <a asp-action="Delete" asp-route-id="@item.VacinaId" class="btn btn-danger">Deletar</a>

                    </td>
                </tr>
            
            </tr>
    }
        </tbody>
    </table>
</div>